import Foundation

// MARK: - App Store metadata field constraints

/// A single App Store metadata field and its App Store Connect length limit.
struct MetadataFieldSpec: Identifiable {
    let key: String
    let label: String
    let maxLength: Int?
    let multiline: Bool
    var id: String { key }
}

enum MetadataPlan {
    /// App Store Connect localized metadata fields with their documented character limits.
    static let fields: [MetadataFieldSpec] = [
        .init(key: "name",            label: "App name",                 maxLength: 30,   multiline: false),
        .init(key: "subtitle",        label: "Subtitle",                 maxLength: 30,   multiline: false),
        .init(key: "promotionalText", label: "Promotional text",         maxLength: 170,  multiline: true),
        .init(key: "description",     label: "Description",              maxLength: 4000, multiline: true),
        .init(key: "keywords",        label: "Keywords (comma-separated)", maxLength: 100, multiline: false),
        .init(key: "whatsNew",        label: "What's New",               maxLength: 4000, multiline: true),
        .init(key: "marketingUrl",    label: "Marketing URL",            maxLength: nil,  multiline: false),
        .init(key: "supportUrl",      label: "Support URL",              maxLength: nil,  multiline: false),
    ]
}

// MARK: - Agent brief generation

/// Everything the agent brief needs. Pure value type so it can be unit-tested.
struct AgentBriefInput {
    var appName: String
    var bundleId: String
    var appId: String
    var versionString: String?
    var goal: String
    var audience: String
    var tone: String
    var principles: String
    var locales: [String]
    var includeCurrent: Bool
    /// locale -> (fieldKey -> value)
    var current: [String: [String: String]]
}

enum AgentBriefBuilder {
    static let briefFileName = "AGENT_BRIEF.md"
    static let planFileName = "metadata.plan.json"

    /// Builds the human/agent-readable instructions document.
    static func markdown(_ input: AgentBriefInput) -> String {
        let locales = input.locales.isEmpty ? ["<add target locales>"] : input.locales
        var s = "# App Store metadata brief\n\n"
        s += "_Generated by ASC Manager. Follow this brief to (re)write all localized App Store metadata, then apply it with the ASC CLI._\n\n"

        s += "## App\n"
        s += "- **Name:** \(input.appName)\n"
        s += "- **Bundle ID:** \(input.bundleId)\n"
        s += "- **App ID:** \(input.appId)\n"
        if let v = input.versionString { s += "- **Version:** \(v)\n" }
        s += "\n"

        s += "## Goal & positioning\n\(nonEmpty(input.goal))\n\n"
        s += "## Target audience\n\(nonEmpty(input.audience))\n\n"
        s += "## Tone & voice\n\(nonEmpty(input.tone))\n\n"
        s += "## Principles / do's & don'ts\n\(nonEmpty(input.principles))\n\n"

        s += "## Target locales\n"
        for l in locales { s += "- \(l)\n" }
        s += "\n"

        s += "## Fields & limits (hard caps from App Store Connect)\n"
        s += "| Field | Max length | Notes |\n|---|---|---|\n"
        for f in MetadataPlan.fields {
            let max = f.maxLength.map { "\($0) chars" } ?? "—"
            let note = f.multiline ? "multi-line" : "single line"
            s += "| `\(f.key)` (\(f.label)) | \(max) | \(note) |\n"
        }
        s += "\n"

        s += "## Instructions for the agent\n"
        s += """
        1. Read `\(planFileName)` next to this file — it lists every locale, every field, its limit, and the current value (if available).
        2. For **each** locale, write metadata that follows the goal, audience, tone and principles above.
        3. Never exceed a field's max length. Keep keywords as a comma-separated list under the cap, no spaces after commas where possible.
        4. Keep meaning consistent across locales; localize idioms rather than translating literally.
        5. Write the result back into the metadata files in this folder that `asc metadata pull` created (one file per field/locale), or fill the `proposed` map in `\(planFileName)`.
        6. Validate offline before uploading: `asc metadata validate --dir "<this folder>"`.
        7. Dry-run the upload first: `asc metadata apply --app \(input.appId)\(input.versionString.map { " --version \($0)" } ?? "") --dir "<this folder>" --dry-run`.
        8. When the dry-run looks correct, apply for real (drop `--dry-run`).

        """
        return s
    }

    /// Builds the machine-readable plan JSON string the agent fills in.
    static func planJSON(_ input: AgentBriefInput) -> String {
        let locales = input.locales.isEmpty ? [] : input.locales
        let fieldDicts: [[String: Any]] = MetadataPlan.fields.map { f in
            var d: [String: Any] = ["key": f.key, "label": f.label, "multiline": f.multiline]
            if let m = f.maxLength { d["maxLength"] = m }
            return d
        }
        var localeEntries: [[String: Any]] = []
        for locale in locales {
            var entry: [String: Any] = ["locale": locale]
            if input.includeCurrent {
                entry["current"] = input.current[locale] ?? [:]
            }
            // Empty skeleton for the agent to fill.
            var proposed: [String: String] = [:]
            for f in MetadataPlan.fields { proposed[f.key] = "" }
            entry["proposed"] = proposed
            localeEntries.append(entry)
        }
        let root: [String: Any] = [
            "app": ["name": input.appName, "bundleId": input.bundleId, "appId": input.appId,
                    "version": input.versionString ?? ""],
            "goal": input.goal,
            "audience": input.audience,
            "tone": input.tone,
            "principles": input.principles,
            "fields": fieldDicts,
            "locales": localeEntries
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: root,
                                                      options: [.prettyPrinted, .sortedKeys]),
              let str = String(data: data, encoding: .utf8) else { return "{}" }
        return str
    }

    /// Writes both files into `dir`. Returns the brief file URL on success.
    @discardableResult
    static func write(_ input: AgentBriefInput, to dir: String) throws -> URL {
        let dirURL = URL(fileURLWithPath: dir, isDirectory: true)
        try FileManager.default.createDirectory(at: dirURL, withIntermediateDirectories: true)
        let briefURL = dirURL.appendingPathComponent(briefFileName)
        let planURL = dirURL.appendingPathComponent(planFileName)
        try markdown(input).write(to: briefURL, atomically: true, encoding: .utf8)
        try planJSON(input).write(to: planURL, atomically: true, encoding: .utf8)
        return briefURL
    }

    private static func nonEmpty(_ s: String) -> String {
        let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
        return t.isEmpty ? "_(not provided)_" : t
    }
}

// MARK: - Local metadata folder browsing

struct LocalMetadataFile: Identifiable, Hashable {
    let url: URL
    let relativePath: String
    var id: String { url.path }
}

enum LocalMetadataStore {
    static let textExtensions: Set<String> = ["txt", "json", "md", "yml", "yaml", "csv", "strings", "plist"]

    /// Recursively lists editable text files under `dir`, returning paths relative to `dir`.
    static func files(in dir: String) -> [LocalMetadataFile] {
        guard !dir.isEmpty else { return [] }
        let base = URL(fileURLWithPath: dir, isDirectory: true)
        let fm = FileManager.default
        guard let it = fm.enumerator(at: base,
                                     includingPropertiesForKeys: [.isRegularFileKey],
                                     options: [.skipsHiddenFiles]) else { return [] }
        var out: [LocalMetadataFile] = []
        for case let url as URL in it {
            guard textExtensions.contains(url.pathExtension.lowercased()) else { continue }
            let isFile = (try? url.resourceValues(forKeys: [.isRegularFileKey]))?.isRegularFile ?? false
            guard isFile else { continue }
            let rel = url.path.replacingOccurrences(of: base.path + "/", with: "")
            out.append(LocalMetadataFile(url: url, relativePath: rel))
            if out.count >= 2000 { break }   // safety cap
        }
        return out.sorted { $0.relativePath.localizedStandardCompare($1.relativePath) == .orderedAscending }
    }

    static func read(_ file: LocalMetadataFile) throws -> String {
        try String(contentsOf: file.url, encoding: .utf8)
    }

    static func write(_ text: String, to file: LocalMetadataFile) throws {
        try text.write(to: file.url, atomically: true, encoding: .utf8)
    }
}
